## The Graph API Queries
Note that the data provided in The Graph API is not sufficient to analyze leveraged trading

In [1]:
from the_graph_utils import query_swaps, query_orders

In [2]:
swaps = query_swaps()

In [3]:
swaps.head()

,id,account,tokenIn,tokenOut,amountIn,amountOut,amountOutAfterFees,feeBasisPoints,tokenInPrice,timestamp,date
0,0x11e0e6c56de2da8ef667dfb4d22a3f864375e71593e1...,0x5f799f365fa8a2b60ac0429c48b153ca5a6f0cf8,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,10000000000000000,33323107,33226469,29,3350505556850000000000000000000000,1630397792,2021-08-31 08:16:32
1,0xc9a9860a924c22db4d00eb1e7d48811f6f22f4d4a909...,0xabbc5f99639c9b6bcb58544ddf04efa6802f4064,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,10000000,2984000000000000,2975346400000000,29,1000000000000000000000000000000,1630399219,2021-08-31 08:40:19
2,0xb45c0cd26357bf450b8c4bc8980fcf1f1c4957530068...,0xabbc5f99639c9b6bcb58544ddf04efa6802f4064,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f,10000000,20800,20737,30,1000000000000000000000000000000,1630399311,2021-08-31 08:41:51
3,0x88d322d5eafac5a96e0973ea6051c93ebd75ae3db93c...,0x5f799f365fa8a2b60ac0429c48b153ca5a6f0cf8,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,10000000000000000,33323107,33226469,29,3350505556850000000000000000000000,1630399311,2021-08-31 08:41:51
4,0xb4b953e77b76d85640d8428dc557fa9dbbac1db97492...,0xbb00f2e53888e60974110d68f1060e5eaab34790,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f,10000000,20800,20737,30,1000000000000000000000000000000,1630409956,2021-08-31 11:39:16

In [4]:
orders = query_orders()

In [5]:
orders.head()

,id,type,account,status,index,size,createdTimestamp,cancelledTimestamp,executedTimestamp,date
0,0xbb00f2e53888e60974110d68f1060e5eaab34790-swap-0,swap,0xbb00f2e53888e60974110d68f1060e5eaab34790,executed,0,10000000000000000000000000000000,1634639207,NaN,1.634816e+09,2021-10-19 10:26:47
1,0xbb00f2e53888e60974110d68f1060e5eaab34790-swap-1,swap,0xbb00f2e53888e60974110d68f1060e5eaab34790,executed,1,10000000000000000000000000000000,1634639207,NaN,1.634812e+09,2021-10-19 10:26:47
2,0xbb00f2e53888e60974110d68f1060e5eaab34790-dec...,decrease,0xbb00f2e53888e60974110d68f1060e5eaab34790,cancelled,0,13904905839999996860640000000000,1634639663,1.634764e+09,NaN,2021-10-19 10:34:23
3,0xbb00f2e53888e60974110d68f1060e5eaab34790-inc...,increase,0xbb00f2e53888e60974110d68f1060e5eaab34790,executed,0,13980399999999998937500000000000,1634640576,NaN,1.634812e+09,2021-10-19 10:49:36
4,0xbb00f2e53888e60974110d68f1060e5eaab34790-dec...,decrease,0xbb00f2e53888e60974110d68f1060e5eaab34790,executed,1,13979842787400000000000000000000,1634755294,NaN,1.634755e+09,2021-10-20 18:41:34

## GMX Backend Queries

In [18]:
import json
import pandas as pd
from websocket import create_connection

In [12]:
ws = create_connection("wss://www.gmx.house/api-ws")

In [13]:
# query leaderboard
ws.send('{"topic":"requestLeaderboardTopList","body":{"timeInterval":16934400,"offset":0,"pageSize":10000,"sortBy":"realisedPnl","chain":42161,"sortDirection":"desc"}}')

166

In [14]:
result =  ws.recv()

In [17]:
data = json.loads(result)

In [19]:
leaderboard = pd.DataFrame(data['body']['page']).drop(columns=['claim'])

In [20]:
leaderboard

,account,collateral,size,fee,realisedPnl,collateralDelta,sizeDelta,realisedPnlPercentage,winTradeCount,settledTradeCount,openTradeCount
0,0xa7e38489a00e6dd16ff479638b5265cb505a9052,28495471108679317795087911600627863387,638067285062901178603837430353400000000,1323816154441441549475168494765165100,-2872787790525601410766159406716705131,29355295316965940636277718855000000000,644005034332901178603837430353400000000,-20217,18,89,0
1,0xdc0391716f261a9656530e0202a174ffb148d555,17842896559372050142338895630551752984,400873287862472230323546343001600000000,1065787335405791949104070280048317200,-1902438837332172228903086079076163566,18504958112510414718972780620000000000,407875854902472230323546343001600000000,-63016,16,47,0
2,0xbe23cbb62064b8b1550ae5ada59c39d45b1e2081,4944639448625148669017841491595790748,119647456046256398387942298838000000000,344957145453208276524237747190804000,-1605846749413664996733491497853833589,5573780688175003540940710420000000000,128533103386256398387942298838000000000,-181696,12,55,0
3,0x89261103fa88a913c8d0debd00574fd16895407d,1536695417125152680000022526889000000,9427447918919999999997411000000000000,106964070901606919999970664041000000,-1567788388214627697402709726291556164,1618865300000000000000000000000000000,9427447918919999999997411000000000000,-9506,0,1,0
4,0x5b16557f1b63f981d1b4cfad18e7a4d5283fefc6,10443661496856879295316934365306333410,154745364963247424038957479653886590000,663883674520841613884373098723290855,-1207590766332975331653398353830831918,12482603402192407625873491551040220000,154745364963247424038957479653886590000,20688,25,54,0
...,...,...,...,...,...,...,...,...,...,...,...
3517,0x0740902dbe5d30259b387404248a207ab581dd8c,35789553534992629462907476173525868652,74313631530568622346044260544494201208,228396649417916540995278889348484341,179770355861531641036218896207253542,53712983019526178285126959063765000000,110945910417564376505981208159896350000,2292466,219,645,0
3518,0xd4ad5d62dce1a8bf661777a5c1df79bd12ac8f1d,1782770141340563279521343632394543510,17102687435657134282657975995960580000,70134167261699572216431727866372071,227942441173915211439341875364550576,2048789384380000000000000000000000000,17102687435657134282657975995960580000,33202,13,13,0
3519,0x1ea6a6085f2ce3e1f982684a28879761343ff4ce,6746002963764653088993063491933789320,30652735787172720439944138066210680000,106712973960375455407536289455260360,240207869366551037829779713605079101,6776655699551825809433007630000000000,30652735787172720439944138066210680000,-6591,10,28,0
3520,0x9dbed1de02833275673fb87d37a40a6a1d424fcd,6407699812458723550597773402555170000,150913423162917519879252763121000000000,365652008323197822566987286494247000,246834194994609663601845478047233589,6562787636165189960993500400000000000,150913423162917519879252763121000000000,159047,74,117,0
3521,0xff33f5653e547a0b54b86b35a45e8b1c9abd1c46,55580812377863097790232081718858367000,1204157580636120476033006461732400000000,2717642049189793007596057875555108600,1594644587924185632099585278547960961,56798586252906186333470424805000000000,1204157580636120476033006461732400000000,189355,73,275,0

In [ ]:
leaderboard.to_csv('all_time_leaderboard.csv')

In [ ]:
START_TIME = 16934400  # all time

In [ ]:
def get_account_request(account, time_interval):
    return '{"topic":"requestAccountTradeList","body":{"account":"' + str(
        account) + '","timeInterval":' + str(time_interval) + ',"chain":42161}}'

In [ ]:
accounts = leaderboard['account'].to_list()

In [ ]:
dfs = []

In [ ]:
for account in accounts:
    ws.send(get_account_request(account, START_TIME))
    result =  ws.recv()
    data = json.loads(result)
    dfs.append(pd.DataFrame(data['body']))

In [ ]:
trade_data = pd.concat(dfs).reset_index(drop=True)

In [ ]:
trade_data.to_csv('gmx_trade_data.csv')